DIMENSIONS = 80
FOOD_PLACES = 35
FOOD_MAX = 50
HOME_START = DIMENSIONS // 4
NANTS_SQRT = 7
HOME_END = HOME_START + NANTS_SQRT
HOME_RANGE = range(HOME_START, HOME_END)
EVAP_RATE = 0.99
ANT_SLEEP = 0.005
PHEROMONE_SCALE = 10.
C2P = 10  # cell 2 pixel

RESOLUTION = DIMENSIONS * C2P
